name: app
description: "Mobile App"
publish_to: 'none'
version: 3.1.1+7

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^10.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.0
  hydrated_bloc: ^10.0.0
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  equatable: ^2.0.7
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  flutter_launcher_icons: ^0.14.3
  skeletonizer: ^2.0.0-pre
  firebase_core: ^3.13.0
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  firebase_messaging: ^15.2.5
  shared_preferences: ^2.5.3
  table_calendar: ^3.1.3
  crypto: ^3.0.6
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/languages/
    - assets/icon/icon.png

flutter_native_splash:
  color: "#F9F9FF"
  image: assets/icon/black-logo.png
  color_dark: "#111318"
  image_dark: assets/icon/white-logo.png

  android_12:
    color: "#F9F9FF"
    image: assets/icon/black-logo.png
    color_dark: "#111318"
    image_dark: assets/icon/white-logo.png

  web: false