name: Create Tag on Merge to Main
on:
  push:
    branches:
      - main
jobs:
  create_and_push_tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git user
        run: |
          git config user.name "Konrad Krawczyk"
          git config user.email "konrad.krawczyk@icloud.com"
      - name: Get latest tag and increment
        id: tag_version
        run: |
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest found tag: $latest_tag"
          
          version_core=${latest_tag#v}

          IFS='.' read -ra parts <<< "$version_core"
          major=${parts[0]:-0}
          minor=${parts[1]:-0}
          patch=${parts[2]:-0}

          new_patch=$((patch + 1))
          new_tag="v${major}.${minor}.${new_patch}"

          echo "New tag: $new_tag"
          echo "new_tag_value=$new_tag" >> $GITHUB_OUTPUT
      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_TAG: ${{ steps.tag_version.outputs.new_tag_value }}
        run: |
          echo "Creating tag $NEW_TAG"
          git tag -a "$NEW_TAG" -m "New tag $NEW_TAG generated by GitHub Actions."
          git push origin "$NEW_TAG"
          echo "Tag $NEW_TAG has been push successfully."